### ISSUE TITLE
Feature Request: Set up database

### ISSUE THREAD

**Issue by SeanSpires** [se701-group6/A2#18]
**User Story**
As a back-end developer
I want a database to store user information.

**Priority**
[x]: High
[]: Medium
[]: Low

**Describe the solution you want to implement**
A means for the server to store and retrieve user information 

**Describe alternatives you've considered**
Logan brought up a solution in which we don't need to use a database at all. Will require a further discussion about this alternative.

**Issue Dependencies**
none

**Additional context**
none

**Comment by lken274** [comment]
Just as a note to discuss what this database should contain:
Using a local db should be fine for this application, python standard library has sqlite3 already.

We'll need a table for user login information.

We'll also need at least one table for payment history, we discussed two solutions at the design meeting. One approach is that we have no concept of an entire bill, but only one table which consists of individual payments which are related using the bill_id as the key. The other is that we have separate tables for bills and payments, have a one-to-many relationship between them.

I also think we should have two .db files (one for accounts, one for payments) because it further decouples the work done between whoever's assigned to the different API endpoints.

**Comment by tant836** [comment]
Peer programming 2 assignees. This will also include getter and setter functions, so end points don't have to do in line sql.
